### ISSUE TITLE
v0.1.0 To-Do List

### ISSUE THREAD

**Issue by sophiebremer** [typescriptlibs/tsl-mastodon-api#7]
- [x] Add POST tests
   - [x] Media attachment test
   - [x] Poll vote test
   - [x] Status test
- [x] Add support for HTML responses
   - [x] Add JSON-based HTML types (AST)
   - [x] Add HTML-to-JSON converter
   - [x] Improve REST.fetch
- [x] Add support for Mastodon lists
   - [x] Add type verification
   - [x] Add get / post functions
   - [x] Add get / post tests
- [x] Update package
   - [x] Update dependencies
   - [x] Update version in package.json
   - [x] `npm i`
   - [x] Update version in SECURITY.md
   - [x] Add marker commit with new version right before release
- [x] Publish NPM package
